# Generated by Django 4.1 on 2023-05-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.ManyToManyField(blank=True, to='blog.comment'),
        ),
    ]
